[Git]
Repo = "https://github.com.cnpmjs.org/dengzii/blog-article.git"
AccessToken = ""
Dir = "E:/www/repo"

[Blog]
Host = "0.0.0.0"
Port = 8080
Template = "./template"
Dir = "E:/www/out"
WebHookAccessToken = "abcd"