name: Publish & Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    name: blogger
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Get Tag
        id: get_tag
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
          echo blogger_${GITHUB_REF/refs\/tags\//}.tar.gz


      - name: Set Up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.16

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GitAction }}
        with:
          tag_name: ${{ github.ref }}
          release_name: release_${{ steps.get_tag.outputs.TAG }}
          draft: false
          prerelease: false

      - name: build TAR PACKAGE
        run: tar -czvf go_im.tar.gz blogger

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GitAction }}
        with:
          tag_name: ${{ github.ref }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./blogger.tar.gz
          asset_name: blogger_${{ steps.get_tag.outputs.TAG }}.tar.gz
          asset_content_type: application/gzip

